pattern matches substring "foobar" at 0
subexpression (foo) matched target substring "foo" at 0
subexpression ((bar)*) matched target substring "bar" at 3
subexpression (bar) matched target substring "bar" at 3

pattern matches substring "baz" at 6
subexpression (baz) matched target substring "baz" at 6

pattern matches substring "foo" at 9
subexpression (foo) matched target substring "foo" at 9
subexpression ((bar)*) matched target substring "" at 12

pattern matches substring "baz" at 12
subexpression (baz) matched target substring "baz" at 12

