0: usr
1: login	bob
1: id
2: usr	123
2: grp	456
1: name	Robert E. Lee
1: logdir	/usr/bob
1: shell	/bin/ksh
0: foo
1: bar	10
0: usr
1: login	slv
1: id
2: usr	194
2: grp	100
1: name	Susan L. Vogel
1: logdir	/usrs8/slv
1: shell	/usr/tools/bin/ksh
0: foo
1: bar	20
0: usr
1: login	ark
1: id
2: usr	49180
2: grp	155
1: name	Koenig
1: logdir	/usrs11/ark
0: usr
1: login	hotshot
1: id
2: usr	181
2: grp	158
1: name	john snare
1: logdir	/usrs2/awb/hotshot
1: shell	/usr/tools/bin/ksh
