#!/bin/sh
#/*ident	"@(#)cls4:tools/pt/tool1	1.3" */
#######################################################################
#
# C++ source for the C++ Language System, Release 3.0.  This product
# is a new release of the original cfront developed in the computer
# science research center of AT&T Bell Laboratories.
#
# Copyright (c) 1993  UNIX System Laboratories, Inc.
# Copyright (c) 1991, 1992 AT&T and UNIX System Laboratories, Inc.
# Copyright (c) 1984, 1989, 1990 AT&T.  All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE of AT&T and UNIX System
#	
# Laboratories, Inc.  The copyright notice above does not evidence
# any actual or intended publication of such source code.
#
#######################################################################

# display the template class for each instantiation file
# in the repository

PATH=/bin:/usr/bin:/usr/ucb

pn=`basename $0`

rep=$1

if [ "$rep" = "" -o ! -d "$rep" ]
then
	echo "usage: $pn repository" 1>&2
	exit 1
fi

cd $rep

ls *.c |

while read fn
do
	n=`sed -n '1s/^\/\* \(.*\) \*\/$/\1/p' $fn`
	echo "$fn  -->  $n"
done

exit 0
