#!/bin/sh
#/*ident	"@(#)cls4:tools/pt/tool2	1.3" */
#######################################################################
#
# C++ source for the C++ Language System, Release 3.0.  This product
# is a new release of the original cfront developed in the computer
# science research center of AT&T Bell Laboratories.
#
# Copyright (c) 1993  UNIX System Laboratories, Inc.
# Copyright (c) 1991, 1992 AT&T and UNIX System Laboratories, Inc.
# Copyright (c) 1984, 1989, 1990 AT&T.  All Rights Reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE of AT&T and UNIX System
#	
# Laboratories, Inc.  The copyright notice above does not evidence
# any actual or intended publication of such source code.
#
#######################################################################

# export contents of repository into an archive

PATH=/bin:/usr/bin:/usr/ucb

pn=`basename $0`

t=/tmp/$pn.$$
trap "rm -rf $t; exit 2" 1 2 3 15
rm -rf $t
mkdir $t

if [ $# -ne 2 -o ! -d "$1" ]
then
	echo "usage: $pn repository archive"
	exit 1
fi

n=1
for i in $1/*.o
do
	cp $i $t/${n}.o
	n=`expr $n + 1`
done

rm -f $2
ar cr $2 $t/*.o
if [ -x /bin/ranlib -o -x /usr/bin/ranlib ]
then
	ranlib $2
fi

rm -rf $t

exit 0
